version: '3.9'

services:

  web-server:
    # profiles: [ "apache" ]
    # profiles: [ "wordpress" ]
    build:
      dockerfile: .docker/Dockerfile-web-server
      context: .
      args:
        DOCKER_PROJECT_PUBLIC_PATH: ${DOCKER_PROJECT_PUBLIC_PATH}
        DOCKER_PROJECT_PHP_VERSION: ${DOCKER_PROJECT_PHP_VERSION}
        DOCKER_PROJECT_NODEJS_VERSION: ${DOCKER_PROJECT_NODEJS_VERSION}
        DOCKER_PROJECT_ENV: 'local'
    # env_file: './projects/.env.variables'
    stdin_open: true
    tty: true
    volumes:
      - '.docker/conf/php.ini:/usr/local/etc/php/conf.d/php.ini'
      - './projects/${DOCKER_PROJECT_NAME}:/var/www/html'
    ports:
      - '80${DOCKER_PROJECT_PORT}:80'
      - '90${DOCKER_PROJECT_PORT}:443'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db-mysql:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password --sql_mode=
    environment:
      - MYSQL_DATABASE=${DOCKER_PROJECT_NAME}
      - MYSQL_USER=docker_user
      - MYSQL_PASSWORD=docker_password
      - MYSQL_ROOT_PASSWORD=docker_password
    volumes:
      - db_data_mysql:/var/lib/mysql
    ports:
      - '61${DOCKER_PROJECT_PORT}:3306'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db-mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 1000M
    ports:
      - '51${DOCKER_PROJECT_PORT}:80'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web-adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db-mysql
    volumes:
      - '.docker/conf/php.ini:/usr/local/etc/php/conf.d/php.ini'
    ports:
      - '52${DOCKER_PROJECT_PORT}:8080'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db-postgres:
    image: postgres:10.1
    environment:
      - POSTGRES_DB=${DOCKER_PROJECT_NAME}
      - POSTGRES_USER=docker_user
      - POSTGRES_PASSWORD=docker_password
    volumes:
      - db_data_postgres:/var/lib/postgresql/data
      - db_data_postgres_backup:/var/lib/postgresql/backup
    ports:
      - '62${DOCKER_PROJECT_PORT}:5432'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web-pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '53${DOCKER_PROJECT_PORT}:80'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web-phppgadmin:
    restart: always
    image: dockage/phppgadmin:latest
    ports:
      - '54${DOCKER_PROJECT_PORT}:80'
    environment:
      - PHP_PG_ADMIN_SERVER_HOST=db-postgres
      - PHP_PG_ADMIN_SERVER_PG_DUMP_PATH=/usr/bin/pg_dump
      - PHP_PG_ADMIN_SERVER_PG_DUMPALL_PATH=/usr/bin/pg_dumpall
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db-redis:
    image: redis:latest
    ports:
      - '63${DOCKER_PROJECT_PORT}:6379'
    extra_hosts:
      - "host.docker.internal:host-gateway"

#  mailhog:
#    image: 'mailhog/mailhog:latest'
#    ports:
#      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
#      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
#    networks:
#      - projects

volumes:
  db_data_mysql:
    name: 'db-data-mysql-${DOCKER_PROJECT_NAME}'
  db_data_postgres:
    name: 'db-data-postgres-${DOCKER_PROJECT_NAME}'
  db_data_postgres_backup:
    name: 'db-data-postgres-backup-${DOCKER_PROJECT_NAME}'

#networks:
#  projects:
#    driver: host