ARG DP_PUBLIC_PATH
ARG PHP_IMAGE
ARG NODEJS_IMAGE
ARG DOCKER_PROJECT_ENV

FROM ${PHP_IMAGE}

ARG DP_PUBLIC_PATH
ARG PHP_IMAGE
ARG NODEJS_IMAGE
ARG DOCKER_PROJECT_ENV

ENV DP_PUBLIC_PATH $DP_PUBLIC_PATH
ENV PHP_IMAGE $PHP_IMAGE
ENV NODEJS_IMAGE $NODEJS_IMAGE
ENV DOCKER_PROJECT_ENV $DOCKER_PROJECT_ENV

WORKDIR /var/www/html

# Установка прав доступа (linux ubuntu)
RUN groupmod -g 1000 www-data && \
    usermod -u 1000 -g 1000 www-data &&\
    usermod --shell /bin/bash www-data && \
    usermod -d /var/www/html www-data

# Установка программ и утилит
RUN apt-get update && apt-get install -y \
    sudo \
    curl \
    wget \
    g++ \
    git \
    cron \
    nano \
    libbz2-dev \
    libfreetype6-dev \
    libonig-dev \
    libicu-dev \
    libjpeg-dev \
    libmcrypt-dev \
    libpng-dev \
    libreadline-dev \
    libjpeg62-turbo-dev \
    jpegoptim optipng pngquant gifsicle \
    libc-client-dev  \
    libkrb5-dev \
    zlib1g-dev \
    libzip-dev \
    zip \
    unzip \
    supervisor \
 && rm -rf /var/lib/apt/lists/*

# https://www.marco.zone/official-docker-php-apache-https
# SSL 443
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/ssl-cert-snakeoil.key -out /etc/ssl/certs/ssl-cert-snakeoil.pem -subj "/C=AT/ST=Vienna/L=Vienna/O=Security/OU=Development/CN=example.com"
RUN a2enmod rewrite
RUN a2ensite default-ssl
RUN a2enmod ssl

RUN apt-get update
RUN apt-get -y upgrade

ENV NODEJS_IMAGE_URL=https://deb.nodesource.com/setup_${NODEJS_IMAGE}.x

RUN echo $NODEJS_IMAGE
RUN echo $NODEJS_IMAGE_URL

RUN curl -sL "$NODEJS_IMAGE_URL" | sudo bash -
RUN apt-get --yes --force-yes install nodejs

# Install gulp & bower
RUN npm install --global electron-forge
RUN npm install --global gulp
RUN npm install --global grunt
RUN npm install --global bower
RUN npm install --global less
RUN npm install --global sass

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Устанавливаем путь к обработке папки "public"
RUN sed -ri -e 's!/var/www/html!/var/www/html/${DP_PUBLIC_PATH}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/html!/var/www/html/${DP_PUBLIC_PATH}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

RUN a2enmod rewrite headers
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini" || true

# Установка расширений PHP
# RUN docker-php-ext-install gd
# RUN docker-php-ext-install bz2

RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl
RUN docker-php-ext-install imap

RUN docker-php-ext-install intl
RUN docker-php-ext-install iconv
RUN docker-php-ext-install opcache
RUN docker-php-ext-install bcmath
RUN docker-php-ext-install mysqli pdo pdo_mysql
RUN apt-get install -y libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql
RUN docker-php-ext-install zip

# RUN docker-php-ext-install mbstring
# RUN docker-php-ext-enable imap
# RUN docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/

# Set storage to writable
# COPY . /var/www/html/
# RUN chmod -R 777 storage/
