ARG PROJECT_PUBLIC_PATH
ARG NODEJS_VERSION

FROM ubuntu:latest

ARG PROJECT_PUBLIC_PATH
ARG NODEJS_VERSION

ENV PROJECT_PUBLIC_PATH $PROJECT_PUBLIC_PATH
ENV NODEJS_VERSION $NODEJS_VERSION

CMD ["sleep", "infinity"]
WORKDIR /var/www/html
RUN groupadd --gid 1000 project
RUN useradd --uid 1000 --gid project --shell /bin/bash --create-home project

RUN apt-get update && apt-get install -y \
    sudo \
    curl \
    wget \
    g++ \
    git \
    unzip \
    zip \
 && rm -rf /var/lib/apt/lists/*

ENV NODEJS_VERSION_URL=https://deb.nodesource.com/setup_${NODEJS_VERSION}.x
RUN curl -sL "$NODEJS_VERSION_URL" | sudo bash -
RUN apt-get install -y nodejs

# Install gulp & bower
RUN npm install --global electron-forge
RUN npm install --global gulp
RUN npm install --global grunt
RUN npm install --global bower