FROM php:8.1-apache

WORKDIR /var/www/html

RUN groupmod -g 1000 www-data && \
    usermod -u 1000 -g 1000 www-data &&\
    usermod --shell /bin/bash www-data && \
    usermod -d /var/www/html www-data

# Установка программ и утилит
RUN apt-get update && apt-get install -y \
    nano \
    smbclient \
    iputils-ping
#    curl \
#    wget
# && rm -rf /var/lib/apt/lists/*

# RUN apt install smbclient libsmbclient-dev
# RUN pecl install smbclient
# RUN docker-php-ext-enable smbclient
# RUN docker-php-ext-install smbclient

